user:
  name:
    length: 50
  email:
    length: 50
    case_sensitive: false
  password:
    length: 6
  gravatar:
    size: 80
  edit:
    emails: "http://gravatar.com/emails"

root:
  my: "my"
  locales: "locales"
  rb_yml: "*.{rb,yml}"
